rest:
  global:
    request:
      method: method name
      path: url path
    response:
      body: response body
      bodyFile: response body as file
      status: http status
      headers: # Map
        header-key: header-value
  endpoints: # List of Endpoint Models
    - request:
        method: method name
        path: url path
      response:
        body: response body
        bodyFile: response body as file
        status: http status
        headers: # Map
          header-key: header-value
  entities: # List of Entity Models
    - name: entity name (used as path)
      dataAll: data of all entities (Array of objects)
      dataNew: object for POST request
      id: id property in object
